site_name: Amanbolat's notes
site_url: https://notes.amanbolat.com
repo_url: https://github.com/amanbolat/notes
site_description: A Collection of Useful Notes about Programming and Related Topics
copyright: |
  Copyright &copy; 2023 <a href="https://github.com/amanbolat"  target="_blank" rel="noopener">Amanbolat</a>

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - toc.follow
    - content.tabs.link
    - search.share
    - search.highlight
    - search.suggest

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
